# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def sum_even_fib():
    f0 = 1
    f1 = 1
    fib_next = 0

    fib_sum = 0

    while fib_next < 4000000:
        fib_next = f1 + f0

        if fib_next % 2 == 0:
            fib_sum += fib_next

        f0 = f1
        f1 = fib_next

    return fib_sum


print(sum_even_fib())
